version: "3.5"

services:
  wxservice:
    build: .
    ports:
      - "7001:7001"
    container_name: "wxservice"
    volumes:
      - "/etc/localtime:/etc/localtime"
    environment:
      - PORT=7001
      - TOKEN=ilovehuyue
      - ID=gh_fec02afadc2e
      - APPID=wx6d47f55f0b0216f2
      - SECRET=f3d6b0d9896a5edd66ea6a538c8d4a40
      - DB_USER=root
      - DB_PWD=
      - DB_URL=mysql:3306
      - DB_NAME=wx
    networks:
      - default
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: "wx_mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "~/mysql/weixin:/var/lib/mysql"
    networks:
      - default
